export const courseConfig = {
  title: "Design with AI for Public Service",
  program: "NYU Tandon IDEA",
  semester: "Summer 2026",
  dates: "June 30 – July 11, 2026",
  location: "Room 802, 8th Floor, 2 MetroTech Center",
  locationUrl: "https://maps.app.goo.gl/mqp5qPqKUTTjF7e96",
  times: "9:00 AM – 4:00 PM",
  syllabusUrl: "https://docs.google.com/document/d/1aTd0T2W7iC23pgt7bjsH93Q8sSEi2wDs-uzoND5l7Dc/edit?usp=sharing",
  schedule: [
    {
      week: 1,
      day: 1,
      date: "June 30",
      weekday: "Tue",
      theme: "What has AI already done to our life?",
      available: true,
    },
    {
      week: 1,
      day: 2,
      date: "July 1",
      weekday: "Wed",
      theme: "Public service + AI",
      available: true,
    },
    {
      week: 1,
      day: 3,
      date: "July 2",
      weekday: "Thu",
      theme: "Think like a founder",
      available: false,
    },
    {
      week: 2,
      day: 4,
      date: "July 7",
      weekday: "Mon",
      theme: "Market analysis",
      available: false,
    },
    {
      week: 2,
      day: 5,
      date: "July 8",
      weekday: "Tue",
      theme: "Design an AI solution",
      available: false,
    },
    {
      week: 2,
      day: 6,
      date: "July 9",
      weekday: "Wed",
      theme: "Responsible human judgment",
      available: false,
    },
    {
      week: 2,
      day: 7,
      date: "July 10",
      weekday: "Thu",
      theme: "Build + prototype",
      available: false,
    },
    {
      week: 2,
      day: 8,
      date: "July 11",
      weekday: "Fri",
      theme: "Pitch day",
      available: false,
    },
  ],
} as const

export type ScheduleDay = (typeof courseConfig.schedule)[number]
