export const courseConfig = {
  title: "Design with AI for Public Service",
  program: "NYU Tandon IDEA",
  semester: "Summer 2026",
  dates: "June 29 – July 9, 2026",
  location: "8th Floor, 2 MetroTech Center",
  times: "9:00 AM – 4:00 PM",
  schedule: [
    {
      week: 1,
      day: 1,
      date: "June 29",
      weekday: "Mon",
      theme: "What has AI already done to our life?",
      available: true,
    },
    {
      week: 1,
      day: 2,
      date: "June 30",
      weekday: "Tue",
      theme: "Public service + AI",
      available: false,
    },
    {
      week: 1,
      day: 3,
      date: "July 1",
      weekday: "Wed",
      theme: "Think like a founder",
      available: false,
    },
    {
      week: 1,
      day: 4,
      date: "July 2",
      weekday: "Thu",
      theme: "Market analysis",
      available: false,
    },
    {
      week: 2,
      day: 5,
      date: "July 6",
      weekday: "Mon",
      theme: "Design an AI solution",
      available: false,
    },
    {
      week: 2,
      day: 6,
      date: "July 7",
      weekday: "Tue",
      theme: "Responsible human judgment",
      available: false,
    },
    {
      week: 2,
      day: 7,
      date: "July 8",
      weekday: "Wed",
      theme: "Build + prototype",
      available: false,
    },
    {
      week: 2,
      day: 8,
      date: "July 9",
      weekday: "Thu",
      theme: "Pitch day",
      available: false,
    },
  ],
} as const

export type ScheduleDay = (typeof courseConfig.schedule)[number]
